name: Release Alpha and Propose Stable

on:
  pull_request:
    types: [closed]
    branches: [dev]
  workflow_dispatch:

jobs:
  publish_alpha:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.user.login != 'allcontributors[bot]' && github.event.pull_request.user.login != 'pre-commit-ci[bot]')
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'hivemind_bus_client/version.py'
      update_changelog: true
      publish_prerelease: true
      changelog_max_issues: 100
